### ISSUE TITLE
Left and right "trigger" not working when buttons

### ISSUE THREAD

**Issue by MB3hel** [electronstudio/sdl2gdx#10]
The left and right trigger changes are firing no events when they are buttons (like on Logitech Runblepad 2 or older PS2 controllers) instead of actual axes. I'm looking into this. Polling has the right value.

**Comment by MB3hel** [comment]
Looks like this is because they are reported as buttons by the Joystick API, but are treated as axes by the gamepad api. The `numAxes` and `numButtons` values indicate that the L2 and R2 "buttons" are being counted as buttons when the `axisState` array is created in the `SDL2Controller` class.

**Comment by MB3hel** [comment]
Any easy fix might be something like:
SDL2Controller.java - In constructor
```
if(SDL.SDL_IsGameController(device_index)) {
    controller = SDL_GameController.GameControllerOpen(device_index);
    
    // Always 6 axes for an SDL2 GameController
    axisState = new float[6];
    
    // Should do the same with the buttons to prevent some dpad directions (eg only up) from firing buttonDown or buttonUp events
    // Always 11 buttons on an SDL2 GameController
    buttonState = new boolean[joystick.numButtons()];
    
    // At this point might as well do it for the hats too
    // Always 1 hat on SDL2 GameController (treated as four buttons)
    hatState = new PovDirection[1];
}else{
    controller = null;
    
    // Values can vary for SDL2 Joystick
    axisState = new float[joystick.numAxes()];
    buttonState = new boolean[joystick.numButtons()];
    hatState = new PovDirection[joystick.numHats()];
}
```

**Comment by electronstudio** [comment]
I think you are right that we should always set ```axisState = new float[6]``` for SDL_GameControllers .

I'm undecided about the number of buttons and hats....

The goal is to use the SDL_GameController API for all devices that support it, and fall back to SDL_Joystick API if a device does not.

It seems SDL_GameController doesn't have hats, everything is either an axis or a button, including the dpad.  So I think the dpad directions *should* fire button events.  Strictly speaking we shouldn't even provide PovDirection!  The reason we do provide it of course is that it is part of the GDX API.

So, I guess getPov() could test if we have an SDL_GameController and just return 0 because in that case the user should be checking for Buttons not Pov?  On the other hand other GDX implementations might be returning Povs for these controllers so someone switching from such an implementation might expect it.  But then, like you, might they be surprised by the button events also firing?  Argh.

**Comment by electronstudio** [comment]
anyway does that fix the triggers?

**Comment by MB3hel** [comment]
That fixes the L2 and R2 buttons. Thanks.

As for the button/dpad issue I would suggest that it is always best to only have the API behave one way. In this case the way the listener functions is dictated by GDX. So I would say that the dpad should always use `povChanged` and never use `buttonDown` and `buttonUp`. A listener that has "dynamic" behavior is likely just to cause confusion for users and more work for developers.

I do, however, also agree that when the device is a game controller it should _internally_ use the dpad buttons instead of using the joystick API. Setting the `buttonState` array length to 11 will prevent the dpad button changes from firing events (this will keep the listener behavior consistent with the joystick API and with GDX), but it does not prevent using `getButton` to get the POV direction instead of the wrapped joystick.

For a game controller with only one supported POV just set the `hatState` array length to 1. Then in the `getPOV` function use the controller API if the device is a controller. This is the same sort of method I see in use in `getButton` and `GetAxis`

SDL2Controller.java - getPOV
```java
if(controller != null){
    boolean up = getButton(SDL.SDL_CONTROLLER_BUTTON_DPAD_UP);
    boolean down = getButton(SDL.SDL_CONTROLLER_BUTTON_DPAD_UP);
    boolean left = getButton(SDL.SDL_CONTROLLER_BUTTON_DPAD_UP);
    boolean right = getButton(SDL.SDL_CONTROLLER_BUTTON_DPAD_UP);
    
    if(up){
        if(left) return PovDirection.northWest;
        else if(right) PovDirection.northEast;
        else return PovDirection.north;
    }else if(down){
        if(left) return PovDirection.southWest;
        else if(right) PovDirection.southEast;
        else return PovDirection.south;
    }else if(left){
        return PovDirection.west;
    }else if(right){
        return PovDirection.east;
    }
    return return PovDirection.center;
    
}else if(joystick!=null){
    switch (joystick.getHat(povCode)) {
        case SDL_HAT_UP:
            return PovDirection.north;
        case SDL_HAT_DOWN:
            return PovDirection.south;
        case SDL_HAT_RIGHT:
            return PovDirection.east;
        case SDL_HAT_LEFT:
            return PovDirection.west;
        case SDL_HAT_RIGHTUP:
            return PovDirection.northEast;
        case SDL_HAT_RIGHTDOWN:
            return PovDirection.southEast;
        case SDL_HAT_LEFTUP:
            return PovDirection.northWest;
        case SDL_HAT_LEFTDOWN:
            return PovDirection.southWest;
        default:
            return PovDirection.center;
    }
}
return PovDirection.center;
```
This allows using the GameController API internally, but does not create a dynamic behavior for users.

**Comment by MB3hel** [comment]
Leaving it as it is now causes only some dpad directions to fire button events. Changing it as described above causes them never to fire (only use povChanged). Using 15 as the `buttonState` array length would allow all to fire (and just keep using the joystick api for povChanged). This would also work, but it means that the dpad events may or may not fire based on the device, so I suspect that `povChanged` would likely just be used anyways. I also don't think having dpad button events fired would be to confusing to GDX users. Button events are going to be filtered by buttonCode anyways so just ignore the dpad events just like with any other unused button.

**Comment by electronstudio** [comment]
I agree with your approach, I think I've done what you suggested in b96085c but sorry I haven't had time to test so let me know if I missed anything

**Comment by electronstudio** [comment]
Also sorry that commit is completely unreadable due to whitespace changes.  The only code changes are getPov and the constructor.

**Comment by MB3hel** [comment]
That looks right to me.
