### ISSUE TITLE
Rumble doesn't work on macOS

### ISSUE THREAD

**Issue by rafaskb** [electronstudio/sdl2gdx#11]
Calling the suggested method to trigger the rumble effect on a controller simply doesn't work on macOS (10.14.4).

```java
RumbleController rumbleController = (RumbleController) controller;
boolean success = rumbleController.rumble(1, 1, 500);
```

Note that the variable `success` is always true.

I'm using the lwjgl2 backend, and libgdx version 1.9.9.

**Comment by electronstudio** [comment]
What is the controller?  Does it work in other SDL apps?  I've tested with Dual Shock 4 and Xbone One Elite connected via USB on MacOS 10.12.6.

**Comment by electronstudio** [comment]
I think to get the Xbox working on Mac I had to install https://github.com/360Controller/360Controller/releases

**Comment by electronstudio** [comment]
If you want to ensure the problem is with sdl2gdx and not your code, there is a test app you can run with:
`./gradlew runTester` 

It has a button to test rumble.

**Comment by rafaskb** [comment]
Oh sorry I forgot to inform the controller I'm using, it's an Xbox One Wireless controller (which means it doesn't need that driver, all other Xbox controllers do, though).

I'll test the official test application ASAP and let you know how it goes. 😄

**Comment by electronstudio** [comment]
I have also tested with "Microsoft X-Box One S pad" which does seem to use that driver.  I don't have the non-S non-Elite version.

**Comment by rafaskb** [comment]
Alright, first of all my bad, I made a typo on the name of the controller I'm using, it is the Xbox One **S** Wireless, the white one, non-Elite, made by Microsoft.

I ran the `runTester` task and here's the result:
- In Wireless mode, all inputs work perfect, but Rumble doesn't, with any intensity, and not even with `Xinput enable`. This is the case both with and without the "360Controller" driver you mentioned.
- In Wired mode, now with the "360Controller" driver enabled (because otherwise the controller is not even recognized by the OS), everything works perfectly, including Rumble.

It would be ideal if Rumble also worked in Wireless mode, since it's the only way to get Xbox controllers to work on macs natively.

I'm quite impressed how everything works out of the box and even with correct mappings though, excellent library!

**Comment by electronstudio** [comment]
Thanks.

This must be a limitation of SDL so it would be up to them to fix.

However they may not be able to.  I suspect that the reason this controller works without any additional drivers on Mac is that it falls back to a bluetooth HID mode rather than the XInput mode it uses on Windows.  So it may just not support rumble in this mode.
