### ISSUE TITLE
Strip release natives

### ISSUE THREAD

**Issue by PokeMMO** [electronstudio/sdl2gdx#13]
Add `-Drelease=true` to each executeAnt's arguments

https://github.com/electronstudio/sdl2gdx/blob/master/src/com/studiohartman/jamepad/JamepadNativesBuild.java#L107

Brings windows64's dll from 11MB to 1.3MB.

Support for this was either added in 1.9.9 or 1.9.10, I can't remember.

**Comment by electronstudio** [comment]
Seems to require jnigen 1.9.10.  Seems to work.  It's in the version now on Github (which is updated to SDL 2.0.12), will do a release soon if no bugs reported.

**Comment by electronstudio** [comment]
released
