### ISSUE TITLE
LigbGDX App crashes when controller is removed.

### ISSUE THREAD

**Issue by kennycason** [electronstudio/sdl2gdx#16]
Hi, Originally I started out using MrStahlfelge's controller library which uses Jamepad which uses sdl2gdx when I noticed my app crashes when unplugging the controller. I then decided to try sdl2gdx and it turned out that the issue still happened. 

My original issue was posted here: https://github.com/MrStahlfelge/gdx-controllerutils/issues/17

It seems that this is a Mac issue. Is this a known issue? Would you like more details?

Thanks for all the awesome work, otherwise everything has been awesome!

**Comment by kennycason** [comment]
I ultimately resolved this issue by updating Jamepad. Not sure if related.

**Comment by electronstudio** [comment]
Jamepad does not use sdl2gdx, they are separate projects.  The only code they have in common is the build script.  So if the problem happens with both I would guess it's an SDL issue.  If you can reproduce the issue with the current version of either of them then yes I would like details please.

**Comment by electronstudio** [comment]
I was going to try updating to the latest snapshot of SDL but it seems this is still an unresolved issue in SDL: https://bugzilla.libsdl.org/show_bug.cgi?id=4961  So there's probably nothing that an SDL-wrapper like sdl2gdx or jamepad can do about it.

Personally I think game developers can't be expected to continually keep up with Apple's latest breakage of the month.  If I do a Mac release of my games now it will be unofficial and I won't vouch to support them.  I'll still do what I can to make sdl2gdx work on Mac though.

**Comment by electronstudio** [comment]
updated to SDL 2.0.12.  works for me on mac.
