### ISSUE TITLE
hotplug doesnt work on Linux

### ISSUE THREAD

**Issue by electronstudio** [electronstudio/sdl2gdx#6]
I guess it's an SDL issue, but it might be how we are building SDL.  If anyone actually uses Linux please investigate this!

**Comment by MrStahlfelge** [comment]
I can confirm the problem, it's the same with the build by the original author.

It's not an SDL issue, hotplugging works with other SDL games on Linux.

**Comment by MB3hel** [comment]
This is an issue I've run into before on linux with native SDL2 apps (C/C++). I seem to remember it working if I used the distribution provided packages, but not if I used packages build with a package manager called conan. It seems like a build options issue with whatever version of SDL jamepad's library is linked with to me.

**Comment by MB3hel** [comment]
I did some further testing and found that if I build SDL v2.0.11 (on Ubuntu 18.04) with the following commands (executed in SDL2 directory)

```
./configure CFLAGS="-fPIC" CPPFLAGS="-fPIC"
make
sudo make install
```

Then building sdl2gdx (only for linux with my testing)

In sdl2gdx directory. Tested with 1.0.3

```
./gradlew linuxNatives
# This errors because of a classpath issue. Is solved it with the following two commands, but this is certainly not the right way to fix it
mkdir build/classes/main
cp -r build/classes/java/main/* build/classes/main
./gradlew linuxNatives
./gradlew uberJar
```

I used the resulting jar (`build/libs/sdl2gdx.jar`) in my app and hotplug worked correctly.

**Comment by MB3hel** [comment]
Also, on the bright side my trackpad was not identified as a joystick device when using this version of SDL2, but this is a different issue.

**Comment by MB3hel** [comment]
Alright, in order to try to maximize compatibility (along with the idea from [here](https://github.com/williamahartman/Jamepad/issues/18)) I built the same thing using Ubuntu 14.04 (chroot environment so a minimal install) with SDL 2.0.10 (stable release this time instead of using latest source code). 

Building sdl2 (in sdl2 directory)

```
./configure CFLAGS="-fPIC" CPPFLAGS="-fPIC" --disable-audio --disable-render --disable-power --disable-filesystem
make
sudo make install
```

Building sdl2gdx (1.0.3 tag): again only linux for testing

```
./gradlew linuxNatives
./gradlew uberJar
```

I built my test app against the resulting `sdl2gdx.jar` file.
Once again hotplug works fine. All testing was done on my Ubuntu 18.04 install (without any version of SDL installed)

**Comment by MB3hel** [comment]
If it helps, here is my `sdl2gdx.jar` after I added Windows and macOS natives.


[sdl2gdx-custom1.0.3-linuxhotplug.zip](https://github.com/electronstudio/sdl2gdx/files/3792173/sdl2gdx-custom1.0.3-linuxhotplug.zip)

**Comment by electronstudio** [comment]
Thanks for doing that.  I can confirm your jar works for me on Debian 10 so I will include that in next release.

**Comment by electronstudio** [comment]
I have updated Github version to SDL 2.0.12 and hotplug seems to work for me.  If no bugs are reported will do a release soon.

**Comment by electronstudio** [comment]
released
