### ISSUE TITLE
ControllerListener initial connect events not fired.

### ISSUE THREAD

**Issue by MB3hel** [electronstudio/sdl2gdx#7]
When using a `ControllerListener` the `connected` method is not run for the controllers that are connected when the `SDL2ControllerManager` is initialized. This is due to the fact that the constructor of the `SDL2ControllerManager` runs the internal `connected` function. As this occurs in the constructor the listener cannot be added until after the internal `connected` function (which should call the listener) has already been run for already connected devices. 

Two simple solutions for this could be 
- A different function to "open" or "init" the `SDL2ControllerManager` after the object is constructed (thus allowing an `addListener` call between creation and polling for connected devices).
- Allow a listener or set of listeners to be passed to an overload constructor which would set the listener(s) before calling the other constructor.

**Comment by MB3hel** [comment]
If there is no opposition to changing this I can create a pull request with either method. Any preferences as to a fix or any reason this should not be changed?

**Comment by electronstudio** [comment]
I'll look into it.  One reason I might not have noticed this is that SDL connected events seem totally unreliable even when using C so I just don't use them.  Sometimes you get two events for one connection, sometimes none.

**Comment by electronstudio** [comment]
Method 1 would require changes to the com.badlogic.gdx.controllers.ControllerManager API, which we can't change because we're not GDX, i.e. we would no longer be compatible with LibGDX.

Method 2 would work.  But again it seems like something that anyone who was used to using the GDX API would just write their own method for.  That's what I do.

How about I add that method to sdl2gdx?  It would be this:
``` 
public void addListenerAndRunForConnectedControllers(ControllerListener listener){
        for(Controller controller : controllers){
            listener.connected(controller);
        }
        addListener(listener);
}
```

**Comment by MB3hel** [comment]
That would also fix the problem. Its also simple enough to just loop through the controllers after creating the manager, I just thought having the listener event fired for already connected controllers would be more consistent with how SDL2 treats add and remove events.

**Comment by MB3hel** [comment]
If it is difficult to support with GDX I wouldn't worry about it. It just seemed like an unexpected behavior to me.

**Comment by MrStahlfelge** [comment]
It's the normal behaviour for libGDX on all other platforms, too. Changing this would lead to a different behaviour on desktop when using this lib.
