### ISSUE TITLE
Southwest does not work on dpad (reports center instead)

### ISSUE THREAD

**Issue by MB3hel** [electronstudio/sdl2gdx#9]
This affects muliple controllers including a Logitech Rumblepad 2, a Sony PS3 controller, Sony PS4 controller, etc. This does not happen with a native SDL2 program using game controllers I have on the same machine. This affects Windows and macOS (and likely Linux as well, but I haven't tested yet). 

I believe that the value for SDL_HAT_LEFTDOWN (SDL class) should be 0x0C (decimal 12) not 0x12(decimal 18). This is based on the output form running 
```
System.out.println(((SDL2Controller)controller).joystick.getHat(0));
```

**Comment by electronstudio** [comment]
thanks for finding these, i'm an idiot!
